// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Videotheque.Model;

namespace Videotheque.Migrations
{
    [DbContext(typeof(VideothequeDbContext))]
    [Migration("20190402090623_mig01")]
    partial class mig01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("Videotheque.Model.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Libelle");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Videotheque.Model.GenreMedia", b =>
                {
                    b.Property<int>("MediaId");

                    b.Property<int>("GenreId");

                    b.HasKey("MediaId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GenreMedias");
                });

            modelBuilder.Entity("Videotheque.Model.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<string>("DateReleae");

                    b.Property<int>("Duration");

                    b.Property<string>("ImagePath");

                    b.Property<int>("LanguageMedia");

                    b.Property<int>("LanguageSubtitles");

                    b.Property<int>("LanguageVO");

                    b.Property<int>("MinAge");

                    b.Property<bool>("NumericalSupport");

                    b.Property<bool>("PhysicalSupport");

                    b.Property<int>("Rated");

                    b.Property<bool>("Seen");

                    b.Property<string>("Synopsis");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("MediaId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Videotheque.Model.GenreMedia", b =>
                {
                    b.HasOne("Videotheque.Model.Genre", "Genre")
                        .WithMany("GenreMedias")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Videotheque.Model.Media", "Media")
                        .WithMany("GenreMedias")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
